// Direct test of write_file
println!("{}", "Testing write_file directly...");

let test_content = "// Generated by GUL compiler\nfn main() {\n    println!(\"Hello from generated code!\");\n}\n";

let success = write_file("direct_test.rs", test_content);
println!("{}", "Write result:", success);

let exists = file_exists("direct_test.rs");
println!("{}", "File exists:", exists);

if exists {
    let content = read_file("direct_test.rs");
    println!("{}", "Content:", content);
}